### ISSUE TITLE
Unsupported op(s) found in input graph

### ISSUE THREAD

**Issue by hhojatansari** [Xilinx/graffitist#6]
ValueError: Unsupported op(s) found in input graph: {'Rsqrt', 'Minimum'}; exiting

**Comment by sjain-stanford** [comment]
@hhojatansari You may bypass this op validity check by providing the `--superuser` flag to `graffitize.pyc`, however keep in mind that such ops will remain untouched (and hence not quantized) by Graffitist. The intent to make this an explicit error rather than a silent warning is so users tread with caution.
